name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libgtest
      run: sudo apt-get install libgtest-dev
    - name: install cmake
      run: sudo apt-get install cmake
    - name: cd to gtest
      run: cd /usr/src/gtest
    - name: make build directory
      run: sudo mkdir build
    - name: cd build
      run: cd build
    - name: cmake
      run: sudo cmake /usr/src/gtest
    - name: make
      run: sudo make
#    - name: cd to gtest
#      run: cd /usr/src/gtest
#    - name: cmake run
#      run: sudo cmake /usr/src/gtest/CMakelists.txt
    - name: make install
      run: sudo make  Makefile
    - name: compile
      run: g++ -Wall -L/usr/src/gtest/build.lib/ -g -pthread gtest.cpp -lgtest -lgtest_main   -lpthread 
    - name: make check
      run: ./a.out

