name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt install libgtest-dev cmake
      run: cd /usr/src/gtest
      run: sudo cmake CMakeLists.txt
      run: sudo make
sudo cp *.a /usr/lib
    - name: configure
      run: g++ -Wall -g -pthread gtest.cpp -lgtest_main  -lgtest -lpthread 
    - name: run the program
      run: ./a.out
