name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get the googletest
      run: wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - name: extract
      run: tar xf release-1.8.0.tar.gz
    - name: change directory
      run: cd googletest-release-1.8.0
    - name: cmake
      run: cmake -DBUILD_SHARED_LIBS=ON .
    - name: make
      run: make
    - name: copy googletest
      run: sudo cp -a googletest/include/gtest /usr/include
    - name: copy gmock
      run: sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
    - name: make install
      run: make install
    - name: cc
      run: g++ -Wall -g -pthread gtest.cpp -lgtest_main  -lgtest -lpthread 
    - name: make check
      run: ./a.out

