name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - name: compile
      run: clang++ -pthread -fsanitize=fuzzer /home/runner/work/Project_Fuzz/Project_Fuzz/fuzzgtest.cpp -lgtest -lgtest_main
    - name: execute
      run: ./a.out
   # - uses: actions/checkout@v3
   # - name: step1
   #   run: git clone https://github.com/google/googletest
   # - name: step 2
   #   run: cd googletest
   # - name: step3
   #   run: mkdir build
   # - name: step3.5
   #   run: cd build
   # - name: step 4
   #   run: cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/work/Project_Fuzz/Project_Fuzz ../googletest
   # - name: step5
   #   run: make -j`nproc`
   # - name: step6
   #   run: cd ~
   # - name: compile
   #   run: g++ -L/home/runner/work/Project_Fuzz/Project_Fuzz/lib/ -Wall -g -pthread gtest.cpp -lgtest_main  -lgtest   -lpthread 
   # - name: execute
   #   run: ./a.out
   #

